#!/usr/bin/env fish

# Set the directory paths for the project and its includes
set python_dir (pwd)"/tests/python"

true

and conda activate ./.conda_environment
and cd $python_dir
and ipython3 never.py
